public class Constants {
    public static final String REST_CLIENT_FIRST_NAME_KEY = 'client_first_name';
    public static final String REST_CLIENT_SECOND_NAME_KEY = 'client_last_name';
    public static final String REST_APPOINTMENT_DATE_KEY = 'appointment_date';
    public static final String REST_START_TIME_KEY = 'start_time';
    public static final String REST_END_TIME_KEY = 'end_time';
    public static final String REST_ACCOUNT_NAME_KEY = 'account_name';
    public static final String REST_APPOINTMENT_KEY = 'Appointment';
    public static final String REST_STATUS_KEY = 'Status';
    public static final String REST_MESSAGE_KEY = 'Message';
    public static final String SUCCESS_MESSAGE = 'Success';

    public static final String TIME_REGEX = '([0-9]{2}:)?[0-9]{2}:[0-9]{2}';
}
